#!/usr/bin/env python3
"""sort an adblock list"""

from datetime import datetime, timezone
from typing import List
from urllib.parse import urlparse
import os
import re
import sys


def process_adblock_list(adblock_list: List[str], header: str, filename: str) -> None:
    """sort and write the adblock list"""
    with open(filename, "w", encoding="utf-8") as file:
        file.write(
            header.replace(
                "DATETIME",
                datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S+00:00"),
            )
        )
        previous_hostname = None
        for line in adblock_list:
            if (
                line.startswith("[")
                or line.startswith("!")
                or line.startswith("*")
                or re.match(r"^(|\s|\t)+$", line)
            ):
                continue

            url = urlparse(f"https://{line}")
            if url.hostname == previous_hostname:
                file.write(f"{line}\n")
            else:
                file.write(f"\n{line}\n")
                previous_hostname = url.hostname


if __name__ == "__main__":
    path = sys.argv[1]
    header_path = sys.argv[2]
    if not (os.path.exists(path) or os.path.exists(header_path)):
        print("usage: adblock-list-sort LIST_PATH HEADER_PATH")
        sys.exit(1)

    with open(path, "r", encoding="utf-8") as f:
        dark_mode_list = f.read().splitlines()
        dark_mode_list.sort()

    with open(header_path, "r", encoding="utf-8") as f:
        header_str = f.read()

    process_adblock_list(dark_mode_list, header_str, path)
